import os

DATA_BUCKET_NAME = os.environ['DATA_BUCKET_NAME']
RENTAL_DATA_KEY = os.environ['RENTAL_DATA_KEY']
ZIPCODE_COVERAGE_KEY = os.environ['ZIPCODE_COVERAGE_KEY']
EMAIL_CREDS_SECRET_NAME = os.environ['EMAIL_CREDS_SECRET_NAME']
